language: java
sudo: true
# dist: trusty

os:
   - linux
  
jdk:
   - openjdk8

install:
   - mvn clean install -DskipTests=true -Dmaven.javadoc.skip=true -B

script:
   # branch enhancement
   - mvn -Dtest=com.SocketTest test